# base image ccr.ccs.tencentyun.com/violin/violin-trade-base
# first stage
FROM python:3.10.8 as builder

RUN python -m pip install --upgrade pip

# to install package and delete tmp files.
# RUN pip install vnpy && find /usr/local/lib -name '*.pyc' -delete
COPY requirements.txt .

RUN pip install -r requirements.txt

# second stage
FROM python:3.10.8-slim

# copy compiled lib from builder
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages

RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen zh_CN.GB18030

RUN mkdir /apps

WORKDIR /apps
